# Project information
site_name: Пишем Telegram-ботов с aiogram 2.x
site_description: Гайд по разработке ботов для Telegram на языке Python с aiogram 2.x
site_author: Groosha
site_url: https://mastergroosha.github.io/aiogram-2-guide
docs_dir: book_src
site_dir: docs

# Repository
repo_name: MasterGroosha/aiogram-2-guide
repo_url: https://github.com/MasterGroosha/aiogram-2-guide
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020-2022 Groosha

# Configuration
theme:
  name: material
  custom_dir: book_src/overrides
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/robot

# Extras
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/joinchat/TsftDfnevFLQS1ts
      name: "Чат в Telegram"
    - icon: fontawesome/brands/github-alt
      link: https://github.com/MasterGroosha/aiogram-2-guide
      name: GitHub

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - meta
  - attr_list
  - toc:
      permalink: true

nav:
  - 'Введение': index.md
  - 'Знакомство с aiogram': quickstart.md
  - 'Работа с собщениями': messages.md
  - 'Кнопки': buttons.md
  - 'Конечные автоматы': fsm.md
  - 'Инлайн-режим': inline_mode.md


plugins:
  - search:
      lang:
        - en
        - ru


# Custom
nav_name: "Оглавление"
